fix: add retry for smoke test backend

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -334,26 +334,26 @@ jobs:
             export API_URL=http://${BACKEND_PUBLIC_IP}:3030
             echo $API_URL
             echo $API_URL/api/status
-            if curl -s $API_URL/api/status | grep "ok"
-            then
-              exit 0
-            else
-              exit 1
-            fi
-            # When the backend server is not ready, let retry upto 30mins
-            # test_result=$(eval curl \
-            #   --verbose --fail \
-            #   --retry 360 --retry-max-time 1800 \
-            #   --url "$API_URL/api/status")
-            # if echo $test_result | grep "ok" > /dev/null
+            # if curl -s $API_URL/api/status | grep "ok"
             # then
-            #   echo "Backend test passed"
-            #   echo $test_result
             #   exit 0
             # else
-            #   echo $test_result
             #   exit 1
             # fi
+            # When the backend server is not ready, let retry upto 30mins
+            test_result=$(eval curl \
+              --verbose --fail \
+              --retry 360 --retry-max-time 1800 \
+              --url "$API_URL/api/status")
+            if echo $test_result | grep "ok" > /dev/null
+            then
+              echo "Backend test passed"
+              echo $test_result
+              exit 0
+            else
+              echo $test_result
+              exit 1
+            fi
       - run:
           name: Frontend smoke test.
           command: |
